version: '3.11'
services:
  jenkins:
    image: jenkins/jenkins:jdk17
    user: "1000:1000"
    ports:      
      - 8080:8080
      - 50000:50000
    volumes:
      - ../jenkins-data:/var/jenkins_home:rw

  backend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    ports:
      - 5000:5000
volumes:
  jenkins-data: